import Card from "@/components/Card"
import Skeleton from "@/components/Skeleton"
import Image from "next/image"
import { Suspense } from "react"
import Loading from "./Loading"

// set static meta data
export const metadata = {
	title: "ISTAD - Home",
	description: "Generated by create next app",
}


export async function fetchData() {
	const res = await fetch(
		"https://api.escuelajs.co/api/v1/products?limit=10&offset=0", { cache: "no-store" }
	)
	const data = await res.json()
	return data
}

export default async function Home() {
	const products = await fetchData()
	console.log(products)
	return (
		<main>
			<div
				className='hero min-h-screen'
				style={{
					backgroundImage: `url("https://sportshub.cbsistatic.com/i/2022/02/16/9125b462-fa85-4cb7-b6d1-09b3e8ed8b5e/marvels-avengers.png")`,
				}}
			>
				<div className='hero-overlay bg-opacity-60'></div>
				<div className='hero-content text-center text-neutral-content'>
					<div className='max-w-md'>
						<h1 className='mb-5 text-5xl font-bold'>Hello there</h1>
						<p className='mb-5'>
							Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
							excepturi exercitationem quasi. In deleniti eaque aut repudiandae
							et a id nisi.
						</p>
						<button className='btn btn-primary'>Get Started</button>
					</div>
				</div>
			</div>

			{/* list product  */}

			<div className='flex flex-wrap justify-center  mx-auto my-16 gap-3'>

				{products.map((product) => (

					<Card
						key={product.id}
						title={product.title}
						desc={product.description}
						img={product.images}
						id={product.id}
						price={product.price}
					/>

				))}

			</div>
		</main>
	)
}
